### ISSUE TITLE
Proguard rules for this library

### ISSUE THREAD

**Issue by SAGARSURI** [patrickfav/armadillo#1]
Is there any proguard rule for this library ?

**Comment by patrickfav** [comment]
If it would, it would provide it's own proguard mapping which the Android Gradle Plugin will honor (see proguard-rules.pro).

Nevertheless this lib does not use reflection, byte code manipulation, code creation or other methods which would require any special treatment. You should be able to obfuscate it 100%

**Comment by SAGARSURI** [comment]
awesome.
