### ISSUE TITLE
Password is not being used for derivating encryption key

### ISSUE THREAD

**Issue by davidmigloz** [patrickfav/armadillo#11]
The user provided password is supposed to be used to derivate the encryption key. However, it seems that currently is not being used.

How to reproduce:
1. Instantiate Armadillo with password A.
2. Save some data
3. Instantiate Armadillo with password B (without deleting data).
4. Try to retrieved data stored with password A.
-> You are able to retrieve the plain data

**Comment by davidmigloz** [comment]
But the fix implies that if someone was using password is not going to be able to decrypt the data anymore :$. Can we migrate the data somehow?

**Comment by patrickfav** [comment]
Hi David thx for the PR.

That looks bad :( I will think about if migration is feasible, otherwise we will have to bump the major version and maybe provide a workaround.

**Comment by davidmigloz** [comment]
Maybe for future migrations, we can start storing the protocol version in the same way the storage salt is stored. So then we can easily check when the protocol version has been bumped and apply the proper data migration. Because currently I have no idea how we can detect it. What do you think?

**Comment by patrickfav** [comment]
I fear the app developer would need to track the migration (e.g. the have a migration flag for all the key/value pairs with user PW, the first time the value is accessed read it with password = null, then write it with the correct pw)

I will release a new version today with a note on the issue and probable migration issues.

**Comment by patrickfav** [comment]
For today there is a 0.5.0 release. Will think about a solution regarding migration the next couple of days.

**Comment by davidmigloz** [comment]
Perfect. Thanks Patrick.

**Comment by davidmigloz** [comment]
We could use the changing password feature #13 to make the migration easier. It would be changing from empty password to the user password.

**Comment by patrickfav** [comment]
Good idea, this would make it more simple.
