### ISSUE TITLE
Please migrate to androidX

### ISSUE THREAD

**Issue by ankur-dev** [patrickfav/armadillo#45]
Hi, Thanks for this Library.

Please migrate to this code to androidx

**Comment by patrickfav** [comment]
The new toolchain seems to have problems with signed jars, didn't try it in a while though, see https://github.com/patrickfav/armadillo/pull/30

**Comment by patrickfav** [comment]
Full disclaimer though: Im not too active in the mobile dev world anymore, so I would appreciate input from the community if this is something you would like to see.

**Comment by ankur-dev** [comment]
will this library work with app bundle?

**Comment by patrickfav** [comment]
Sorry can't say as I do not use it in current projects. Would appreciate input on this matter however.

**Comment by goemic** [comment]
> will this library work with app bundle?

Sure it does! Why shouldn't it?

**Comment by patrickfav** [comment]
Merged with #51
