### ISSUE TITLE
EncryptionProtocolException: at.favre.lib.armadillo.AuthenticatedEncryptionException: could not encrypt

### ISSUE THREAD

**Issue by bhautik-mworldwebtech** [patrickfav/armadillo#48]
SharedPreferences preferences = Armadillo.create(context, prefName)
                .password(Keys.UserProvidedPassword.toCharArray()) //use user provided password
                .securityProvider(Security.getProvider("BC")) //use bouncy-castle security provider
                .keyStretchingFunction(new PBKDF2KeyStretcher()) //use PBKDF2 as user password kdf
                .contentKeyDigest(Bytes.from(getUniqueDeviceId(context)).array()) //use custom content key digest salt
                .secureRandom(new SecureRandom()) //provide your own secure random for salt/iv generation
                .encryptionFingerprint(context, (Keys.EncryptionFingerprint).getBytes(StandardCharsets.UTF_8)) //add the user id to fingerprint
                .supportVerifyPassword(true) //enables optional password validation support `.isValidPassword()`
                .enableDerivedPasswordCache(true) //enable caching for derived password making consecutive getters faster
                .build();

**Comment by patrickfav** [comment]
I need more info than that. Full stack trace, exact usage.

**Comment by patrickfav** [comment]
Since there was no response.
