### ISSUE TITLE
Logo Proposal For armadillo

### ISSUE THREAD

**Issue by iqbalhood** [patrickfav/armadillo#5]
Hello Sir. I'm a UI/UX and Graphics Designer. 
I want propose a logo for your github project.
Would you mind if I propose logo for your application as my Open Source Contribution?

Thanks before.
Regards,
@iqbalhood

**Comment by patrickfav** [comment]
Hi @iqbalhood, thanks for the offer, glad to accept!
Would you like to post the logo here or in private via mail?

**Comment by iqbalhood** [comment]
hink. I will discuss the logo here. But for the original logo file I have created later I will send to your email.

**Comment by iqbalhood** [comment]
Hello sir @patrickfav ,
These are my logo proposal for your application. If there any revision, please just tell it.

![arma1](https://user-images.githubusercontent.com/1563756/42173546-a0106f7e-7e49-11e8-8ca4-ee71c9a92bcf.jpeg)

**Comment by patrickfav** [comment]
Hey @iqbalhood I really like it a lot!

**Comment by iqbalhood** [comment]
hello sir, I have made a pull request for the addition of the logo and modification of the readme.md file here.
https://github.com/patrickfav/armadillo/pull/7

If you need the editable file, you can check it here.
https://drive.google.com/drive/folders/1qSCHpkzyIhPI6Fgzs8mY7QNSHk6yCUTa?usp=sharing

**Comment by patrickfav** [comment]
As the logo is merged I will close this issue.
