### ISSUE TITLE
jBCrypt library requires to pass the password as String object

### ISSUE THREAD

**Issue by davidmigloz** [patrickfav/armadillo#8]
In `BcryptKeyStretcher`, the Char[] array with the password is converted into a String to call the `BCrypt.hashpw()` function:

![image](https://user-images.githubusercontent.com/6546265/42328050-a563bc76-806d-11e8-8bd8-7d55d61c8504.png)

This implies we have no means of clearing the password from memory afterwards, as a String is an immutable value.

https://stackoverflow.com/questions/8881291/why-is-char-preferred-over-string-for-passwords

**Comment by patrickfav** [comment]
Hi David,

Thanks for the review. As this is an issue with the BCrypt library's API and not this one, I suggest you notifiy the developers of jBCrypt https://www.mindrot.org/projects/jBCrypt/
As I see it there is no way around using a String instance with this lib.

**Comment by davidmigloz** [comment]
Hi Patrick,

I see that they have an open issue concerning this topic since 2013: https://code.google.com/archive/p/jbcrypt/issues/8

The project doesn't seem to be very active (latest release in 2015). Maybe we should consider to fork it and fix it ourselves? I'm open to contribute to the project.

Regards!

**Comment by patrickfav** [comment]
Hi David,

I think this is actually a very good idea. It seems jBcrypt is the only implementation for java around? There are some copies:

* https://docs.spring.io/spring-security/site/docs/4.2.5.RELEASE/apidocs/org/springframework/security/crypto/bcrypt/BCrypt.html
* https://directory.apache.org/api/gen-docs/latest/apidocs/org/apache/directory/api/ldap/model/password/BCrypt.html

I would propose a new library with a similar implementation but modern, more flexible API, state of the art security dev features (signed jar, signed commits, java 7 min). I would very welcome your contribution.

I started a boilerplate project here: https://github.com/patrickfav/bcrypt.git

**Comment by patrickfav** [comment]
Fixed by #17
